repos:
  # Secret detection for HIPAA compliance
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # Python code quality
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', '.']
        exclude: 'tests/.*'

  # General file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        exclude: cloudformation/alphavox-infrastructure.yml

  # HIPAA-specific: PHI/PII detection
  - repo: local
    hooks:
      - id: phi-pii-check
        name: PHI/PII Detection
        entry: bash -c 'if grep -rn --include="*.py" --include="*.md" --include="*.txt" --include="*.json" -E "(ssn|social.security|patient.id|medical.record|date.of.birth|dob|phone.number|email.*@)" . --exclude-dir=.git --exclude-dir=node_modules; then echo "❌ Potential PHI/PII detected! Review before committing."; exit 1; fi'
        language: system
        pass_filenames: false
