branch-defaults:
  main:
    environment: alphavox-production
    group_suffix: null
  develop:
    environment: alphavox-staging
    group_suffix: null

deploy:
  artifact: deploy.zip

global:
  application_name: AlphaVox
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-alphavox
  sc: git
  workspace_type: Application